# Generated by Django 4.2.5 on 2023-10-05 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_department_studentid_student_user_alter_student_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='studentId',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Id', to='home.studentid'),
        ),
    ]
